### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by Wzedlare** [XPerience-AOSP-Lollipop/android_device_motorola_cedric#1]
Please fix commit ovnerships, I know that repo is kanged from mine.

**Comment by Klozz** [comment]
I dont know ask to @CarlosArriagaCM  him was pushed it.
And I don't know the original repo sorry :/

**Comment by Wzedlare** [comment]
No problem buddy, just fix authorship and everything will be ok.I can't make you do it but this is not being professional.Professionals care about ownerships

**Comment by Klozz** [comment]
Fixed
